// src/utils/rbac.ts

export type RoleType = 
  | 'SUPERADMIN' 
  | 'INVENTORY_DEPARTMENT' 
  | 'ACCOUNTS_DEPARTMENT' 
  | 'CLIENT_ADMIN' 
  | 'CLIENT_BRANCH_USER';

export const PERMISSIONS = {
  // Products
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  BULK_DELETE_PRODUCT: 'BULK_DELETE_PRODUCT',
  RESTORE_PRODUCT: 'RESTORE_PRODUCT',
  VIEW_PRODUCT: 'VIEW_PRODUCT',

  // Inventory / Stock
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  SEARCH_INVENTORY: 'SEARCH_INVENTORY',
  VIEW_STOCK_LEVEL: 'VIEW_STOCK_LEVEL',
  CREATE_STOCK_IN_TXN: 'CREATE_STOCK_IN_TXN',
  CREATE_STOCK_OUT_REQ: 'CREATE_STOCK_OUT_REQ',
  CREATE_DAMAGE_REQ: 'CREATE_DAMAGE_REQ',
  CREATE_REPAIR_REQ: 'CREATE_REPAIR_REQ',
  CREATE_RETURN_INTAKE_REQ: 'CREATE_RETURN_INTAKE_REQ',
  MANAGE_STOCK_REQUEST: 'MANAGE_STOCK_REQUEST',
  APPROVE_STOCK_REQUEST: 'APPROVE_STOCK_REQUEST',
  PRINT_LABEL: 'PRINT_LABEL',

  // Users & Customers
  MANAGE_USER: 'MANAGE_USER',
  MANAGE_CUSTOMER: 'MANAGE_CUSTOMER',
  MANAGE_CUSTOMER_BRANCH: 'MANAGE_CUSTOMER_BRANCH',
  MANAGE_CUSTOMER_LOGIN: 'MANAGE_CUSTOMER_LOGIN',
  CREATE_BRANCH_USER: 'CREATE_BRANCH_USER',
  EDIT_BRANCH_USER: 'EDIT_BRANCH_USER',
  DISABLE_BRANCH_USER: 'DISABLE_BRANCH_USER',

  // Orders
  CREATE_ORDER: 'CREATE_ORDER',
  CREATE_ORDER_BEHALF: 'CREATE_ORDER_BEHALF',
  APPROVE_ORDER: 'APPROVE_ORDER',
  REJECT_ORDER: 'REJECT_ORDER',
  MODIFY_ORDER_QTY: 'MODIFY_ORDER_QTY',
  ADD_CUSTOM_ITEM: 'ADD_CUSTOM_ITEM',
  VIEW_ORDER: 'VIEW_ORDER',
  VIEW_APPROVED_ORDER: 'VIEW_APPROVED_ORDER',
  VIEW_CUSTOMER_ORDER: 'VIEW_CUSTOMER_ORDER',
  VIEW_COMPANY_ORDER: 'VIEW_COMPANY_ORDER',
  VIEW_COMPANY_BRANCH_ORDER: 'VIEW_COMPANY_BRANCH_ORDER',

  // Dispatches
  CREATE_DISPATCH: 'CREATE_DISPATCH',
  UPDATE_DISPATCH_STATUS: 'UPDATE_DISPATCH_STATUS',
  VIEW_DISPATCH: 'VIEW_DISPATCH',

  // Invoices & Ledger
  GENERATE_INVOICE: 'GENERATE_INVOICE',
  UPLOAD_INVOICE_PDF: 'UPLOAD_INVOICE_PDF',
  VIEW_INVOICE: 'VIEW_INVOICE',
  MANAGE_CUSTOMER_LEDGER: 'MANAGE_CUSTOMER_LEDGER',
  VIEW_OUTSTANDING_AMOUNT: 'VIEW_OUTSTANDING_AMOUNT',
  VIEW_CUSTOMER_STATEMENT: 'VIEW_CUSTOMER_STATEMENT',
  VIEW_STATEMENT: 'VIEW_STATEMENT',

  // Payments
  UPLOAD_PAYMENT_REF: 'UPLOAD_PAYMENT_REF',
  VERIFY_PAYMENT_REF: 'VERIFY_PAYMENT_REF',
  MARK_PAYMENT_RECEIVED: 'MARK_PAYMENT_RECEIVED',
  VERIFY_PAYMENT: 'VERIFY_PAYMENT',

  // Returns
  CREATE_RETURN: 'CREATE_RETURN',
  APPROVE_RETURN: 'APPROVE_RETURN',
  REJECT_RETURN: 'REJECT_RETURN',
  VIEW_RETURN_REQUEST: 'VIEW_RETURN_REQUEST',

  // Pricing
  MANAGE_CUSTOMER_PRICING: 'MANAGE_CUSTOMER_PRICING',
  VIEW_CUSTOMER_SPECIFIC_PRICING: 'VIEW_CUSTOMER_SPECIFIC_PRICING',
  VIEW_CUSTOMER_PRICING: 'VIEW_CUSTOMER_PRICING',

  // Catalog & Stock
  VIEW_PRODUCT_CATALOGUE: 'VIEW_PRODUCT_CATALOGUE',
  VIEW_AVAILABLE_STOCK: 'VIEW_AVAILABLE_STOCK',

  // Reports & Audits
  VIEW_REPORT: 'VIEW_REPORT',
  EXPORT_REPORT: 'EXPORT_REPORT',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
  ACCESS_ALL_MODULES: 'ACCESS_ALL_MODULES'
} as const;

export type PermissionType = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<RoleType, PermissionType[]> = {
  SUPERADMIN: Object.keys(PERMISSIONS) as PermissionType[],

  INVENTORY_DEPARTMENT: [
    'VIEW_INVENTORY',
    'SEARCH_INVENTORY',
    'VIEW_PRODUCT',
    'VIEW_STOCK_LEVEL',
    'CREATE_STOCK_IN_TXN',
    'CREATE_STOCK_OUT_REQ',
    'CREATE_DAMAGE_REQ',
    'CREATE_REPAIR_REQ',
    'CREATE_RETURN_INTAKE_REQ',
    'PRINT_LABEL',
    'CREATE_DISPATCH',
    'UPDATE_DISPATCH_STATUS',
    'VIEW_APPROVED_ORDER',
    'VIEW_CUSTOMER_ORDER',
    'VIEW_RETURN_REQUEST',
    'VIEW_ORDER',
    'VIEW_DISPATCH'
  ],

  ACCOUNTS_DEPARTMENT: [
    'VIEW_ORDER',
    'VIEW_DISPATCH',
    'GENERATE_INVOICE',
    'UPLOAD_INVOICE_PDF',
    'VERIFY_PAYMENT_REF',
    'MARK_PAYMENT_RECEIVED',
    'MANAGE_CUSTOMER_LEDGER',
    'VIEW_OUTSTANDING_AMOUNT',
    'VIEW_CUSTOMER_STATEMENT',
    'EXPORT_REPORT',
    'VERIFY_PAYMENT'
  ],

  CLIENT_ADMIN: [
    'VIEW_PRODUCT_CATALOGUE',
    'VIEW_CUSTOMER_SPECIFIC_PRICING',
    'VIEW_AVAILABLE_STOCK',
    'CREATE_ORDER',
    'CREATE_RETURN',
    'UPLOAD_PAYMENT_REF',
    'VIEW_INVOICE',
    'VIEW_DISPATCH',
    'VIEW_STATEMENT',
    'VIEW_OUTSTANDING_AMOUNT',
    'VIEW_COMPANY_ORDER',
    'VIEW_COMPANY_BRANCH_ORDER',
    'CREATE_BRANCH_USER',
    'EDIT_BRANCH_USER',
    'DISABLE_BRANCH_USER'
  ],

  CLIENT_BRANCH_USER: [
    'VIEW_PRODUCT_CATALOGUE',
    'VIEW_CUSTOMER_PRICING',
    'CREATE_ORDER',
    'CREATE_RETURN',
    'UPLOAD_PAYMENT_REF',
    'VIEW_DISPATCH',
    'VIEW_INVOICE',
    'VIEW_STATEMENT'
  ]
};

export function hasPermission(role: string, permission: PermissionType): boolean {
  if (role === 'SUPERADMIN') return true;
  const perms = ROLE_PERMISSIONS[role as RoleType];
  return perms ? perms.includes(permission) : false;
}

export function checkPermission(session: { role?: string; permissions?: string[] } | null, permission: PermissionType): boolean {
  if (!session || !session.role) return false;
  if (session.role === 'SUPERADMIN') return true;
  if (session.permissions) {
    return session.permissions.includes(permission);
  }
  return hasPermission(session.role, permission);
}

export function enforcePermission(session: { role?: string; permissions?: string[] } | null, permission: PermissionType): void {
  if (!checkPermission(session, permission)) {
    throw new Error(`Forbidden: Missing required permission ${permission}`);
  }
}
